### ISSUE TITLE
400 Bad request when Passing authId

### ISSUE THREAD

**Issue by matrad** [SourcePointUSA/android-cmp-app#682] opened 2023-08-17 10:15 UTC
Hello,

we pass the Auth-ID to the Sourcepoint SDK, what is in our case `1ba4549f-3baa-4ab8-8ea2-8a94dca94924`.
In this case we get a 400 Bad Request in the Logcat Console:

```
 2023-08-17 12:09:33.524 28277-28505/com.xxx.xxx V/sourcepoint: onError: {"err":"{\"msg\":\"http://internal-prod-ccpa-private-193268982.us-east-1.elb.amazonaws.com/ccpa/consent/18191/consent-status?authId=1ba4549f-3baa-4ab8-8ea2-8a94dca94924&hasCsp=false&clientIP=xxx.xxx.xxx.xxx returned a 400\",\"status\":400}"}
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err: com.sourcepoint.cmplibrary.exception.RequestFailedException: {"err":"{\"msg\":\"http://internal-prod-ccpa-private-193268982.us-east-1.elb.amazonaws.com/ccpa/consent/18191/consent-status?authId=1ba4549f-3baa-4ab8-8ea2-8a94dca94924&hasCsp=false&clientIP=xxx.xxx.xxx.xxx returned a 400\",\"status\":400}"}
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.network.util.ResponseManagerImpl.parseConsentStatusResp(ResponseManagerImpl.kt:91)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl$getConsentStatus$1.invoke(NetworkClientImpl.kt:135)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl$getConsentStatus$1.invoke(NetworkClientImpl.kt:118)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.check(FunctionalUtils.kt:33)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl.getConsentStatus(NetworkClientImpl.kt:118)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:162)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:135)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(Unknown Source:0)
 2023-08-17 12:09:33.525 28277-28505/com.xxx.xxx W/System.err:     at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
```

When making the request without an authID it's working.

What did we wrong?

**Comment by matrad** [comment] 2023-08-24 14:58
@andresilveirah are here any news in this case? As we want to release our App this is currently blocking the Release Process

**Comment by andresilveirah** [comment] 2023-08-25 08:46
Hi @matrad sorry for the delay. We just started to investigate this issue, I expect to have a fix by next week.

**Comment by matrad** [comment] 2023-08-30 09:23
@andresilveirah do you have any news here?

**Comment by andresilveirah** [comment] 2023-08-30 13:09
@matrad yes, we're working on a fix and I'm hoping to have it released by the end of the week.

**Comment by matrad** [comment] 2023-09-04 16:24
@andresilveirah any news on this? sorry that we repeatedly ping you on this case but our customer (what pays for the sourcepoint-library) asks repeatedly for feedback on this issue because they want to release the app what also contains other features

**Comment by andresilveirah** [comment] 2023-09-04 18:18
@matrad my bad, we released a fix for this issue in today's release. Can you confirm `7.3.0` works as you expect?

**Comment by matrad** [comment] 2023-09-05 09:07
@andresilveirah now we get a 404 error:

```
2023-09-05 11:06:38.347 22373-22609/xxx.xxx.xxx W/System.err: com.sourcepoint.cmplibrary.exception.RequestFailedException: {"err":"{\"msg\":\"http://internal-prod-cmp-private-308276059.eu-central-1.elb.amazonaws.com/tcfv2/consent/v3/18191/consent-status?hasLocalData=true&withSiteActions=true&hasCsp=false&dateCreated=2023-08-17T12%3A30%3A18.818Z&clientIP=185.121.101.111&consentUUID=57010444-66e3-4f00-b50b-c08fd672830e returned a 404\",\"status\":404}"}

```

**Comment by andresilveirah** [comment] 2023-09-05 10:41
@matrad that's frustrating. I'm on it. 

Does this happen on a new app install? returning user? Or it doesn't matter?

**Comment by matrad** [comment] 2023-09-05 12:13
@andresilveirah as I see only after an update - when reinstalling the app it works, but we have the issue that the Method `onSpFinished` is not called, after enabling the consent, only this methods are called:

onUIReady
onUIFinished
onAction

With the current release we have this issues:
 - onSpFinished is not called
 - onConsentReady is not called
 - When Setting the Consent to = true, if we open the App again, the consent appears again, but it should be displayed only once

**Comment by matrad** [comment] 2023-09-08 21:42
@andresilveirah any news here?

**Comment by matrad** [comment] 2023-09-15 23:35
@andresilveirah ping

**Comment by SvenChristian** [comment] 2023-09-20 05:55
Hi @andresilveirah,

we try to get out a fix for our iPhone customers, at the moment we generate there bad revenues.
So waiting for this fix costs us acctually money.

So please look to solve the problem now as soon as possible - because it's now already over a month that we are waiting.

Thanks
Sven Christian Plangger
sven.plangger@firstavenue.it

**Comment by carmelo-iriti** [comment] 2023-09-26 13:53
Hi all,

just to have all the correct info, are you talking about android or ios? (our iPhone customers)

**Comment by carmelo-iriti** [comment] 2023-09-27 08:49
@matrad can you please send me your SDK configuration with an email to carmelo@sourcepoint.com?

**Comment by matrad** [comment] 2023-10-06 08:28
@carmelo-iriti do we need to change CMP-Provider and SDK? This issue is now open since August 17 and we've still no solution. This is inacceptable for us!

**Comment by carmelo-iriti** [comment] 2023-10-06 08:35
@matrad I understand that and I'm sorry for the lack of communication from our side, the issue is fixed and I'm currently working on releasing the 7.4.0 version

**Comment by carmelo-iriti** [comment] 2023-10-06 15:21
@matrad we just released the v7.4.0 which contains the fix for your issue, in a couple of hours will be available on maven central

**Comment by matrad** [comment] 2023-10-11 09:08
@carmelo-iriti we've still issues in this release:

This Delegate Methods are Called:
2023-10-11 11:04:04.842 24643-24643/com.keepinmind.stol_mobile V/sourcepoint: onUIReady
2023-10-11 11:04:31.511 24643-25420/com.keepinmind.stol_mobile V/sourcepoint: onAction
2023-10-11 11:04:31.515 24643-24643/com.keepinmind.stol_mobile V/sourcepoint: onUIFinished

This Method is not called:
onConsentReady is not called

Then on every App-Launch the Consent is shown.

Please verify the SDK again.

**Comment by carmelo-iriti** [comment] 2023-10-11 09:18
Hey @matrad ,

This looks something different,

Let's do something different, at this link https://play.google.com/store/apps/details?id=com.sourcepointmeta.metaapp there is our test app, where you can execute your property and then share the entire output containing the log.

Can you please send me the log after you have the issue with this application?

**Comment by matrad** [comment] 2023-10-11 09:27
@carmelo-iriti I just send it to your e-mail

**Closed** 2023-10-11 14:17 UTC
