### ISSUE TITLE
Can't receive the callback of SpClient

### ISSUE THREAD

**Issue by nicktz8** [SourcePointUSA/android-cmp-app#494] opened 2022-05-18 16:23 UTC
**Describe the bug**

The dialog of the GDPR First Layer Message can't be displayed so it leads that the app can't receive the callback of `SpClient`. 

**About your environment**
 - SDK version 6.5.0
 - Device: Pixel5
 - OS: Android 11
 - Library setup: All the setup of the library has followed the guide in README

**To Reproduce**
1. Launch the App
2. Can't see the dialog of GDPR first layer

**Expected behavior**
Receive the callback of `SpClient` in order to process the next step

**Additional context**
After investigation, I guess the root cause might be a failure to create Webview because it is always stuck on this line. (https://github.com/SourcePointUSA/android-cmp-app/blob/develop/cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt#L161).

**Comment by carmelo-iriti** [comment] 2022-05-20 09:32
Hi @nicktz8,

thank you for the message, 

can you please also send us the property name you are using for this use case?

**Comment by carmelo-iriti** [comment] 2022-05-20 10:36
I need more info to verify the issue,  at this stage, using an emulator with the same configuration as described ,  I'm not able to reproduce it.

**Comment by nicktz8** [comment] 2022-05-20 14:31
@carmelo-iriti Thanks for the reply.

The property name is `wsj.android.app`.

I didn't see any error messages. For the message from CmpLogger, the last one is below and I didn't see any other messages after this.
```
computation tag toCampaignModelList msg parsed campaigns
```

FYI, I found the bug can't be reproduced if I delay calling `loadMessage` function for around 3 secs.

**Comment by carmelo-iriti** [comment] 2022-05-20 17:08
@nicktz8 let’s try on that device our troubleshooting app https://play.google.com/store/apps/details?id=com.sourcepointmeta.metaapp&hl=en_AU&gl=US
This app is integrating our SDK and gives us all the logs in real time during the rendering

**Comment by nicktz8** [comment] 2022-05-23 09:30
Thanks, @carmelo-iriti. The logs from troubleshooting app look good. It seems to only happen on the emulator since I couldn't reproduce it on the physical device. I will keep my eyes on it if there are any error messages.

**Comment by carmelo-iriti** [comment] 2022-05-23 09:54
Sure!
For now, I'm not gonna close this issue, let me know if something weird happens 👍🏻

**Comment by carmelo-iriti** [comment] 2022-06-09 08:49
Closing this ticket for inactivity

**Closed by carmelo-iriti** 2022-06-09 08:49 UTC
